"""empty message

Revision ID: f8ffb78d6ab9
Revises: 8672023691a0
Create Date: 2024-10-11 21:57:46.190893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ffb78d6ab9'
down_revision = '8672023691a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('select_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_value_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'selectables', ['default_value_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('select_options', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('default_value_id')

    # ### end Alembic commands ###
