"""empty message

Revision ID: 04983a516a91
Revises: 8bec82676e42
Create Date: 2024-10-12 18:03:26.820987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04983a516a91'
down_revision = '8bec82676e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_authenticated', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('is_authenticated')

    # ### end Alembic commands ###
