"""empty message

Revision ID: 8131262a409b
Revises: f8ffb78d6ab9
Create Date: 2024-10-12 14:20:22.125487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8131262a409b'
down_revision = 'f8ffb78d6ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('representative_name', sa.String(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('internal_sku', sa.String(), nullable=True),
    sa.Column('external_sku', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tagstring', sa.String(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('amount_per_box', sa.Integer(), nullable=True),
    sa.Column('minimum_level', sa.Integer(), nullable=True),
    sa.Column('maximum_level', sa.Integer(), nullable=True),
    sa.Column('days_to_receive', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('weight_unit', sa.String(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('depth', sa.Float(), nullable=True),
    sa.Column('dimensional_unit', sa.String(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('selectables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('inventory_multiplier', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'inventory', ['inventory_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('inventory_multiplier', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'inventory', ['inventory_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('inventory_multiplier')
        batch_op.drop_column('inventory_id')

    with op.batch_alter_table('selectables', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('inventory_multiplier')
        batch_op.drop_column('inventory_id')

    op.drop_table('inventory')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
