"""empty message

Revision ID: 8bec82676e42
Revises: e5bdcc30a2e9
Create Date: 2024-10-12 17:41:13.625776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bec82676e42'
down_revision = 'e5bdcc30a2e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boolean_order_options', schema=None) as batch_op:
        batch_op.drop_constraint('boolean_order_options_service_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'order_services', ['service_id'], ['id'])

    with op.batch_alter_table('date_order_options', schema=None) as batch_op:
        batch_op.drop_constraint('date_order_options_service_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'order_services', ['service_id'], ['id'])

    with op.batch_alter_table('float_order_options', schema=None) as batch_op:
        batch_op.drop_constraint('float_order_options_service_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'order_services', ['service_id'], ['id'])

    with op.batch_alter_table('number_order_options', schema=None) as batch_op:
        batch_op.drop_constraint('number_order_options_service_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'order_services', ['service_id'], ['id'])

    with op.batch_alter_table('order_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'parent_orders', ['parent_order_id'], ['id'])

    with op.batch_alter_table('parent_orders', schema=None) as batch_op:
        batch_op.drop_constraint('parent_orders_service_id_fkey', type_='foreignkey')
        batch_op.drop_column('service_id')

    with op.batch_alter_table('select_order_options', schema=None) as batch_op:
        batch_op.drop_constraint('select_order_options_service_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'order_services', ['service_id'], ['id'])

    with op.batch_alter_table('text_order_options', schema=None) as batch_op:
        batch_op.drop_constraint('text_order_options_service_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'order_services', ['service_id'], ['id'])

    with op.batch_alter_table('textarea_order_options', schema=None) as batch_op:
        batch_op.drop_constraint('textarea_order_options_service_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'order_services', ['service_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('textarea_order_options', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('textarea_order_options_service_id_fkey', 'services', ['service_id'], ['id'])

    with op.batch_alter_table('text_order_options', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('text_order_options_service_id_fkey', 'services', ['service_id'], ['id'])

    with op.batch_alter_table('select_order_options', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('select_order_options_service_id_fkey', 'services', ['service_id'], ['id'])

    with op.batch_alter_table('parent_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('parent_orders_service_id_fkey', 'order_services', ['service_id'], ['id'])

    with op.batch_alter_table('order_services', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_order_id')

    with op.batch_alter_table('number_order_options', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('number_order_options_service_id_fkey', 'services', ['service_id'], ['id'])

    with op.batch_alter_table('float_order_options', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('float_order_options_service_id_fkey', 'services', ['service_id'], ['id'])

    with op.batch_alter_table('date_order_options', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('date_order_options_service_id_fkey', 'services', ['service_id'], ['id'])

    with op.batch_alter_table('boolean_order_options', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('boolean_order_options_service_id_fkey', 'services', ['service_id'], ['id'])

    # ### end Alembic commands ###
