"""empty message

Revision ID: e5bdcc30a2e9
Revises: 231388967cc0
Create Date: 2024-10-12 17:19:41.630894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5bdcc30a2e9'
down_revision = '231388967cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_service_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('services_service_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'services', ['parent_service_id'], ['id'])
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('services_service_id_fkey', 'services', ['service_id'], ['id'])
        batch_op.drop_column('parent_service_id')

    # ### end Alembic commands ###
